### ISSUE TITLE
Truffle hangs and then throws exception when running truffle test

### ISSUE THREAD

**Issue by RFVenter** [trufflesuite/truffle-artifactor#48]
`truffle test`

```
Compiling ./contracts/ExampleToken.sol...
Compiling ./contracts/HMLottery.sol...
Compiling ./test/TestHMLottery.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...
Compiling zeppelin/SafeMath.sol...
Compiling zeppelin/lifecycle/Killable.sol...
Compiling zeppelin/ownership/Contactable.sol...
Compiling zeppelin/ownership/Ownable.sol...
Compiling zeppelin/token/ERC20.sol...
Compiling zeppelin/token/StandardToken.sol...
/usr/lib/node_modules/truffle/node_modules/truffle-solidity-utils/index.js:31
      contract_definition.body.forEach(function(statement) {
                              ^

TypeError: Cannot read property 'forEach' of null
    at /usr/lib/node_modules/truffle/node_modules/truffle-solidity-utils/index.js:31:31
    at tryToString (fs.js:456:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)

```

**Comment by CillyIAAgent** [comment]
So we had the same problem and the reason it happened was that we had a test class with no functions or anything else in it. Once we made a empty function in it the error was gone
